In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
print(np.__version__)

1.23.5


In [7]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
print(type(np.array([1,2,3,4])))

<class 'numpy.ndarray'>


In [9]:
arr1=np.array((1,2,3,4))
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
arr3=np.array([1,2,'hello'])
print(arr3)

['1' '2' 'hello']


In [11]:
print(type(arr3))

<class 'numpy.ndarray'>


**0-D Array** Scalae

In [12]:
print(np.array(2))

2


1-D **Array** Vector

In [13]:
print(np.array((1,2,3,4)))

[1 2 3 4]


**2-D Array** Matrics

In [14]:
mat=np.array([[1,2,3,4],[1,2,3,4]])
print(mat)

[[1 2 3 4]
 [1 2 3 4]]


In [15]:
mat=np.array([[1,2,3,4],[1,2,3,4]])
print(mat)

[[1 2 3 4]
 [1 2 3 4]]


**3-D Array** Tensers

In [16]:
print(np.array([[[1,2,3],[1,2,3]],[[1,3,2],[2,3,1]]]))

[[[1 2 3]
  [1 2 3]]

 [[1 3 2]
  [2 3 1]]]


In [17]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print('_____________')
print(b)
print('_____________')
print(c)
print('_____________')
print(d)

42
_____________
[1 2 3 4 5]
_____________
[[1 2 3]
 [4 5 6]]
_____________
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


**Array Indexing**

In [19]:
a1=np.array([1,2,3,4])
print(a1[0])

1


In [20]:
a1=np.array([1,2,3,4])
print(a1[0:])
print(a1[1])

[1 2 3 4]
2


In [21]:
print(a1[1])

2


In [29]:
a2=np.array([1,2,3,4,5])
print(a2[4]+a2[4])
print(a2[4])

10
5


In [24]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 1])

2nd element on 1st row:  7


In [30]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
#print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
print(arr[0, 1, 2])

6


In [40]:
a3=np.array([[[1,2,3,4],[5,6,7,8]],[[4,3,2,1],[8,7,6,5]]])
print(a3)

[[[1 2 3 4]
  [5 6 7 8]]

 [[4 3 2 1]
  [8 7 6 5]]]


In [44]:
print(a3[1,0,-1])

1


In [45]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [49]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [50]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [55]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:5, 1:4])

[[2 3 4]
 [7 8 9]]
