1D array


In [4]:
import numpy as Np

a=Np.array([1,2,3,4,5,6])
print(a)

print(Np.arange(10))

[1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [17]:
a.shape

(6,)

In [19]:

print("dimention of a:",a.ndim)

dimention of a: 1


Two diamentional array


In [8]:
b=Np.array([[1,2,3],[3,2,1]])
print(b)

[[1 2 3]
 [3 2 1]]


In [24]:
sh=b.shape
print(sh)

(2, 3)


3D array


In [13]:
c= Np.array([[[1,2],[5,6]],[[4,3],[3,4]]])
print(c)


[[[1 2]
  [5 6]]

 [[4 3]
  [3 4]]]


In [25]:
c.shape

(2, 2, 2)

In [26]:
c.ndim

3

# **Various Function**